#!/bin/bash

if ! cat /etc/profile | grep -q "kbd-shortcuts"; then
    echo "xhost not enabled"
    echo "##This line was addded by kbd-shortcuts service" >> /etc/profile
    echo -e "if [ '\$DISPLAY' != '' ]" >> /etc/profile
    echo "then" >> /etc/profile
    echo "  xhost +" >> /etc/profile
    echo "fi" >> /etc/profile
else
    echo "xhost already enabled in /etc/profile"
fi
